# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de57cadb7f27bc5e9f742ff01a2f0e42"
application_url = "https://valiant-benevolence-production.up.railway.app"
embedded = true
name = "TSL WinShirt Custom"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://valiant-benevolence-production.up.railway.app/oauth/callback"
]

[app_proxy]
url = "https://valiant-benevolence-production.up.railway.app/proxy"
subpath = "textilelab"
prefix = "apps"

[webhooks]
api_version = "2026-04"
